---
title: 'Exercício: Fix the Code'
output: html_document
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE, eval=F, include=T)

```
## Preparação para o exercício:

Carregue o _data frame_ _mtcars_

```{r}
data(mtcars)
```

## Encontre o erro em todos os códigos abaixo:

Q1)

```{r}
Head(mtcars)
```

Q2)

```{r}
str(Mtcars)
```

Q3)

```{r}
dim[mtcars]
```

Q4)

```{r}
nomes(mtcars)
```

Q5)

```{r}
head(mtcars, x = 10)
```

Q6)

```{r}
v1 <- ("pato", "cachorro", "minhoca", "lagarto")
```

Q7) 

```{r}
v2 <- c("1", "2", "3", "4")
v1 + 42
```

Q8)

```{r}
v1 <- c("pato", "cachorro", "minhoca", "lagarto"
```

Q9) 

```{r}
v3 <- c(33 31 40 25 27 40)
```

Q10)

```{r}
v1 <- c(pato, cachorro, minhoca, lagarto)
```

Q11)

```{r}
v1 <- c("pato" "cachorro" "minhoca" "lagarto")
```

Q12)

```{r}
v3 <- C(33, 31, 40, 25, 27, 40)
```

Q13)

```{r}
v1 <- c("pato", "cachorro"", "minhoca", "lagarto")
v3 <- c(33, 31, 40, 25, 27, 40)
myData <- data.frame(v1, v3)
```

Q14)

```{r}
v1 <- c("pato", "cachorro", "minhoca", "lagarto")
v4 <- c(33, 31, 40, 25, 27, 40)
myData <- data.frame(v1, v4)
```
Q15)

```{r}
v1 <- c("pato", "cachorro", "minhoca", "lagarto")
v4 <- c(33, 31, 40, 25)
myData <- data.frame(v1 = animal, v4 = idade)
```

Q16)

```{r}
ls
```

Q17)

```{r}
v1 <- c("pato", "cachorro", "minhoca", "lagarto")
sum(v1)
```
