###  FLS 6397 - Introdução à Programação e Ferramentas Computacionais para as Ciências Sociais

- Data: 17/05/2019

## Aula 9 - Strings e Mineração de Textos no R

### Objetivos Gerais

Aprender sobre as diferentes formas de manipular strings e textos no R.

### Roteiro para a aula

Nesta aula veremos 3 pacotes diferentes para trabalhar com texto como dado: _stringr_, que é bastante útil para 'limpeza' de textos; _tm_, que foi durante vários anos o pacote principal para mineração de texto e análise de _corpus_ em R; e _tidytext_, pacote do _tidyverse_ para mineração de texto, bastante recente.

_stringr_ - [Tutorial 19](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial19.html)

_tm_ - [Tutorial 20](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial20.html)

_tidytext_ - [Tutorial 21](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial21.html)

Se houver tempo em sala de aula e você quiser se aprofundar no assunto, leia alguns dos capítulos do livro sobre "tidy" text mining, [Text Mining with R](http://tidytextmining.com/), também disponível em formato bookdown:

- [Capítulo 2 - Análise de Sentimento (com textos em inglês)](http://tidytextmining.com/sentiment.html)

- [Capítulo 3 - Análise de frequência de palavras](http://tidytextmining.com/tfidf.html)

- [Capítulo 4 - Relacionamento entre palavras, n-gramas e correlação](http://tidytextmining.com/ngrams.html)

- [Capítulo 6 - Topic Modeling](http://tidytextmining.com/topicmodeling.html)

