
###  FLS 6397 - Introdução à Programação e Ferramentas Computacionais para as Ciências Sociais

- Data: 22/03/2019

## Aula 1 - Introdução ao curso e R Básico

### Objetivos Gerais

Nesta aula vamos discutir o funcionamento do curso, definir os tópicos e ferramentas que estarão definitivamente no programa, discutir o calendário, apresentar o ambiente de programação e aprender o funcionamento básico da linguagem R.

### Roteiro para a aula

1. Começaremos com apresentação do curso e discussão do programa e do calendário.
2. A seguir, teremos uma rápida exposição sobre o ambiente R e o RStudio.
3. **[Tutorial 1:](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial01.html)** Diferentemente de cursos convencionais de R, nos quais se apresenta primeiro R como linguagem de programação, vamos começar com aquilo que é distintivo em R, que é sua vocação para análise de dados. Em particular, vamos começar trabalhando com _data frames_, que são as matrizes de dados.
4. [Exercício de correção de erros](https://jonnyphillips.github.io/FLS6397_2019/activities/fixthecode1.html): Quando terminar o tutorial, façao exercício abaixo de correção de código.

### Roteiro pós-aula

Como estamos inciando com a linguagem R, ainda não teremos nenhuma atividade de avaliação ou desafio para o intervalo entre a 1a e 2a semanas. Vamos investir em aprender as especificidades da linguagem lendo um livro básico de programação em R.

A tarefa para a semana, portanto, é começar a ler o livro _Hands-on Programming With R_, de Garret Grolemund. Obrigatoriamente, você deve ler o Prefácio e os Capítulos 1 e 2, que compõem a Part I. Idealmente, seria bom avançar nos capítulos da Part II (3 a 6), mesmo sem terminá-los nesta semana (tente ler pelo menos o Capítulo 3). Use como critério de parada o seu limite de compreensão. 

Durante a leitura, não se preocupe se você sentir dificuldade em algum tópico. Os primeiros tutoriais que faremos em sala de aula lidam com a maior parte dos tópicos do livro.

### Recurso para auto-estudo

Há vários materiais, tutoriais e cursos sobre R gratuitos produzidos nos últimos anos. É realmente difícil escolher um para começar. Minha sugestão para quem estiver perdida ou perdido e quiser estudar um pouco mais é fazer o curso "[Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r)" no site Datacamp. Esse é o material que costumo sugerir como "nivelamento" antes de oficinas de R.
