###  FLS 6397 - Introdução à Programação e Ferramentas Computacionais para as Ciências Sociais

- Data: 26/04/2019

## Aula 6 -  Visualização de dados

### Objetivos Gerais

Agora você é especialista em acessar e transformar dados e domina pelo menos duas gramáticas diferentes em R. Mas ainda é difícil se comunicar e visualizar sua análise porque só sabemos apresentar texto e tabelas básicas. Hoje, vamos aprender mais uma gramática da linguagem, `ggplot2` (grammar of graphics). Veremos criar gráficos para visualizar os nossos dados usando este poderoso pacote.

### Roteiro para a aula

1. Faremos uma apresentação rápida sobre _ggplot2_ logo no início da aula.
2. A seguir, faça o [Tutorial 11](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial11.html), que traz uma introdução ao _ggplot2_.
3. Caso não tenha lido, leia capítulos 3, 7 e 28 do livro [R for Data Science](http://r4ds.had.co.nz) sobre _ggplot2_. Se já tiver lido, volte aos capítulos e certifique-se de que não restaram dúvidas antes de prosseguir.
4. Finalmente, faça o [Tutorial 12](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial12.html), que traz mais algums aspectos do _ggplot2_ e aprsenta um outro pacote para visualizações em R, _plotly_

### Roteiro pós-aula

Ainda na segunda-feira colocaremos no ar o Desafio 3. Para o desafio você precisará estar confortável com os seguintes tópicos: aberturas de bases de dados; manipulação de bases de dados com _dplyr_; bases de dados relacionais com _dplyr_; e, finalmente, visualização de dados com _ggplot2_. Este é o momento de tirar dúvidas.

Vamos ler (novamente, se você já leu) capítulo 21, "Iterations", de [R for Data Science](http://r4ds.had.co.nz/iteration.html). O proximo desafio sobre o ggplot2 sera disponivel logo com entrega agendada para 25/05.