---
title: "Quick Analysis of New York Flights Data"
author: "Jonathan"
date: "April 22, 2018"
output: pdf_document
---

```{r, echo=FALSE, warning=F, message=F}
library(tidyverse)
library(nycflights13)
library(knitr)
```

```{r, echo=F}
num_flights <- flights %>% count() #Number of flights

num_airlines <- flights %>% distinct(carrier) %>% count() #Number of airlines

num_origin <- flights %>% distinct(origin) %>% count() #Number of origin airports

num_dest <- flights %>% distinct(dest) %>% count() #Number of destination airports

avg_delay <- flights %>% summarize(avg_delay=mean(dep_delay,na.rm=T)) %>%
  round(1) #Average delay
```

The dataset contains `r num_flights` flights by `r num_airlines` different airlines, flying from `r num_origin` New York airports to `r num_dest` destination airports. The average delay of all flights is `r avg_delay` minutes.

The Table shows the average delay for each New York airport. 

```{r, echo=F}
flights %>% group_by(origin) %>% 
  summarize(avg_delay=mean(dep_delay,na.rm=T)) %>%
  kable(col.names=c("Airport","Average Delay"),digits=1,caption="Average Delay by Airport")
#Table of average delay by origin airport
```

The graph shows the relationship between the time of departure and the departure delay.

```{r, echo=F, warning=F}
flights %>% group_by(origin) %>%
  ggplot() +
  geom_point(aes(x=dep_time,y=dep_delay)) #Relationship betweeen departure time and departure delay

```


