###  FLS 6397 - Introdução à Programação e Ferramentas Computacionais para as Ciências Sociais

- Data: 29/03/2019

## Aula 2 - Do básico ao intermédiário

### Objetivos Gerais

Nesta aula vamos cobrir um conjunto grande de aspectos da linguagem R. Aprenderemos sobre operações matemáticas, inclusive com vetores,  fatores, matrizes e operadores relacionais e lógicos. Mais importante ainda do que tais operações da linguagem, veremos como criar claúsula condicionais, "while" e "for" loops e funções. Com isso, saíremos do "R básico" em direção ao "R intermediário".

### Roteiro para a aula

No início da aula, conversaremos sobre a dificuldade da leitura da primeira semana --  _Hands-on Programming With R_. Por favor, sejam extremamente sinceros e relatem se tiverem tido dificuldade(s). 

Faremos, a seguir, tutorais para aprender sobre os aspectos mais básicos da linguagem. Como ainda estamos "calibrando" o curso para a turma atual, pode ser que alguns de vocês ou não terminem os tutoriais a tempo ou terminem cedo demais. Se você está no primeiro grupo, não se preocupe, e finalize o tutorial em casa. Se você está no segundo, aproveite para avançar nas leituras.

Se você ficou um pouco insegura(o) na aula passada, comece em:

1. Revise rapidamente o Tutorial 1, da aula passada ([Tutorial 1](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial01.html)).

Se a aula passada está clara para você, vá para:

2. [Tutorial 2](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial02.html) assim que chegar em sala de aula. Siga o seu próprio ritmo.

3. [Tutorial 3](https://jonnyphillips.github.io/FLS6397_2019/tutorials/tutorial03.html). Não se preocupe se não acabar em sala de aula.

### Roteiro pós-aula

Siga com a leitura do livro _Hands-on Programming With R_, de Garret Grolemund. Termine a parte II do livro (até capítulo 6) se ainda não tiver acabado e, a seguir, siga até final do livro. Caso esteja com dificuldade na leitura, use como critério de parada o seu limite de compreensão.

### Recurso para auto-estudo

Continua valendo a dica do curso "[Introduction to R](https://www.datacamp.com/courses/free-introduction-to-r)" no site Datacamp para reforçar o que foi aprendido nas duas primeiras aulas. O Tutorial 2 segue este curso como modelo.

Se você quiser estudar um pouco mais sobre operadores e condicionais no R, recomendamos fazer o primeiro capítulo do curso "[Intermedtiante R](https://www.datacamp.com/courses/intermediate-r)" (apenas o primeiro capítulo é gratuito).
